/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Railway.ui;

import javax.swing.*;
import java.time.LocalDate;

import java.util.Date;
import com.Railway.dao.TrainDAO;
import com.sun.rowset.CachedRowSetImpl;
import com.Railway.dto.TrainDTO;

import static com.Railway.ui.UpdateTrain.productCode;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class ReserveSeats extends javax.swing.JPanel {

    String u;
    Double total = 0.0;
    Double delta = 0.0;

    /**
     * Creates new form SalesReport
     */
    public ReserveSeats(String user) {
        initComponents();
              type.removeAllItems();
                    traincode.removeAllItems();
                    source.removeAllItems();
                    dest.removeAllItems();
                    nooftickets.removeAllItems();
        loadCode();
        loadDatas2();
        loadSource();
        loadDest();
        loadDefaultDate();
        noofticks();
              
                    
        u = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        billnolab = new javax.swing.JLabel();
        billNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        salePanel1 = new javax.swing.JPanel();
        productNameLab1 = new javax.swing.JLabel();
        customerNameLab1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        salePanel = new javax.swing.JPanel();
        productCodeLab = new javax.swing.JLabel();
        quantityLab = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        sellingPriceLab = new javax.swing.JLabel();
        productNameLab = new javax.swing.JLabel();
        sellBttn = new javax.swing.JLabel();
        pay = new javax.swing.JLabel();
        customerNameLab = new javax.swing.JLabel();
        traincode = new javax.swing.JComboBox<>();
        productCodeLab1 = new javax.swing.JLabel();
        source = new javax.swing.JComboBox<>();
        productCodeLab2 = new javax.swing.JLabel();
        dest = new javax.swing.JComboBox<>();
        productCodeLab5 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox<>();
        cusname = new javax.swing.JTextField();
        productCodeLab3 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nooftickets = new javax.swing.JComboBox<>();
        clear = new javax.swing.JButton();
        productCodeLab4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 240, 242));

        jLabel1.setFont(new java.awt.Font("Comfortaa", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setText("BOOK YOUR TRAIN");

        jLabel10.setForeground(new java.awt.Color(102, 102, 255));
        jLabel10.setText("booking made easy");

        billnolab.setText("reservationno");

        billNo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        billNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billNoActionPerformed(evt);
            }
        });
        billNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                billNoKeyReleased(evt);
            }
        });

        jLabel3.setText("Date");

        productNameLab1.setBackground(new java.awt.Color(204, 204, 255));
        productNameLab1.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        productNameLab1.setForeground(new java.awt.Color(102, 102, 255));

        customerNameLab1.setBackground(new java.awt.Color(204, 204, 255));
        customerNameLab1.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        customerNameLab1.setForeground(new java.awt.Color(102, 102, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("PLEASE FILL ALL THE FIELDS"));
        jPanel1.setFont(new java.awt.Font("Comfortaa", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        productCodeLab.setText("Train code");

        quantityLab.setText("no of tickets");

        price.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        sellingPriceLab.setText("Fare");

        productNameLab.setBackground(new java.awt.Color(204, 204, 255));
        productNameLab.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        productNameLab.setForeground(new java.awt.Color(102, 102, 255));

        sellBttn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/Railway/ui/images/saleLarge.png"))); // NOI18N
        sellBttn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sellBttnMouseClicked(evt);
            }
        });

        pay.setText("Pay");

        customerNameLab.setBackground(new java.awt.Color(204, 204, 255));
        customerNameLab.setFont(new java.awt.Font("Comfortaa", 0, 14)); // NOI18N
        customerNameLab.setForeground(new java.awt.Color(102, 102, 255));

        traincode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        traincode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traincodeActionPerformed(evt);
            }
        });

        productCodeLab1.setText("class");

        source.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        source.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceActionPerformed(evt);
            }
        });

        productCodeLab2.setText("Destination");

        dest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destActionPerformed(evt);
            }
        });

        productCodeLab5.setText("Source");

        type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeActionPerformed(evt);
            }
        });

        cusname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        cusname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cusnameActionPerformed(evt);
            }
        });

        productCodeLab3.setText("customer name");

        jLabel2.setText("TOTAL");

        nooftickets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        nooftickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noofticketsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout salePanelLayout = new javax.swing.GroupLayout(salePanel);
        salePanel.setLayout(salePanelLayout);
        salePanelLayout.setHorizontalGroup(
            salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salePanelLayout.createSequentialGroup()
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addComponent(productCodeLab2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salePanelLayout.createSequentialGroup()
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(salePanelLayout.createSequentialGroup()
                                .addComponent(productCodeLab5)
                                .addGap(67, 67, 67)
                                .addComponent(productNameLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22))
                            .addGroup(salePanelLayout.createSequentialGroup()
                                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(quantityLab)
                                    .addComponent(productCodeLab1)
                                    .addComponent(productCodeLab)
                                    .addGroup(salePanelLayout.createSequentialGroup()
                                        .addComponent(productCodeLab3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(customerNameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sellingPriceLab)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)))
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(price)
                            .addComponent(type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(source, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(traincode, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cusname)
                            .addComponent(nooftickets, 0, 191, Short.MAX_VALUE)
                            .addComponent(Total)
                            .addGroup(salePanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(pay))
                            .addComponent(sellBttn))))
                .addContainerGap())
        );
        salePanelLayout.setVerticalGroup(
            salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salePanelLayout.createSequentialGroup()
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(salePanelLayout.createSequentialGroup()
                                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cusname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(customerNameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99)
                                .addComponent(productNameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(salePanelLayout.createSequentialGroup()
                                .addComponent(productCodeLab3)
                                .addGap(123, 123, 123)
                                .addComponent(productCodeLab5))))
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(traincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productCodeLab))
                        .addGap(18, 18, 18)
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productCodeLab1))
                        .addGap(18, 18, 18)
                        .addComponent(source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salePanelLayout.createSequentialGroup()
                        .addComponent(dest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sellingPriceLab))
                        .addGap(18, 18, 18)
                        .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityLab)
                            .addComponent(nooftickets, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(productCodeLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(salePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sellBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pay)
                .addGap(127, 127, 127))
        );

        javax.swing.GroupLayout salePanel1Layout = new javax.swing.GroupLayout(salePanel1);
        salePanel1.setLayout(salePanel1Layout);
        salePanel1Layout.setHorizontalGroup(
            salePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salePanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(salePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(salePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productNameLab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customerNameLab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(964, 964, 964)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        salePanel1Layout.setVerticalGroup(
            salePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salePanel1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salePanel1Layout.createSequentialGroup()
                .addGroup(salePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(salePanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(customerNameLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(productNameLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(267, 267, 267))
        );

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        productCodeLab4.setText("Please fill in all the fields");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1466, 1466, 1466)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 218, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel10))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(salePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(billnolab)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(productCodeLab4)
                                        .addGap(209, 209, 209)))
                                .addGap(75, 75, 75)
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addComponent(billNo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(497, 497, 497)
                    .addComponent(jLabel12)
                    .addContainerGap(1897, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel10)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(billNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(billnolab))
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clear)
                        .addComponent(productCodeLab4)))
                .addGap(12, 12, 12)
                .addComponent(salePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(310, 310, 310)
                    .addComponent(jLabel12)
                    .addContainerGap(746, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    int quantity;

    private void traincodeActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            type.removeAllItems();
            
            ResultSet rs = new TrainDAO().getType((String) traincode.getSelectedItem());
            while (rs.next()) {
             //   String sellingPrice = new TrainDAO().getProductSellingPrice((String) traincode.getSelectedItem());
                
            String list1 = rs.getString("type");
            type.addItem(list1);
            type.setEditable(true);
            type.setSelectedItem(null);

            } 
            source.removeAllItems();
            dest.removeAllItems();
            loadSource();
            loadDest();
            locSource();


            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }


    private void billNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_billNoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_billNoKeyReleased

    private void billNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_billNoActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
   clear();
        

    }//GEN-LAST:event_clearActionPerformed

    public void clear()
    {
           price.setText("");
        Total.setText("");
        nooftickets.setSelectedItem(null);
        traincode.setSelectedItem(null);
        cusname.setText("");
        source.setSelectedItem(null);
        dest.setSelectedItem(null);
        type.setSelectedItem(null);
    }
    private void destActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destActionPerformed
        // TODO add your handling code here:
            int sellingPrice = new TrainDAO().getProductSellingPrice((String)source.getSelectedItem(),(String)dest.getSelectedItem(),(String)type.getSelectedItem());
                            price.setText(Integer.toString(sellingPrice));
    }//GEN-LAST:event_destActionPerformed

    private void sourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceActionPerformed
        // TODO add your handling code here:
           
     dest.removeAllItems();
       for(int i=0;i<loc.length;i++)
     {
         if(loc[i].equalsIgnoreCase((String)source.getSelectedItem()))
         {
             while(!loc[i].equalsIgnoreCase(list3))
             {       
            dest.addItem(loc[i+1]);
            i++;
             }
             break;
         }
     }
                            
                            
    }//GEN-LAST:event_sourceActionPerformed

  
    private void sellBttnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sellBttnMouseClicked
        if (dateChooser.getDate() == null || nooftickets.getSelectedItem().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the fields!");
        } else {
            try {

                TrainDTO productdto = new TrainDTO();
                productdto.setSellDate(dateChooser.getDate().toString());
                productdto.setProductCode((String) traincode.getSelectedItem());
                productdto.setBillNo(Integer.parseInt(billNo.getText()));
                int sellingPrice = Integer.parseInt(price.getText());
                int totalRevenue = sellingPrice * Integer.parseInt((String)nooftickets.getSelectedItem());
                productdto.setTotalRevenue(totalRevenue);
                productdto.setQuantity(Integer.parseInt((String)nooftickets.getSelectedItem()));
                productdto.setType((String)type.getSelectedItem());
                productdto.setCusname(cusname.getText());
                productdto.setSource((String)source.getSelectedItem());
                productdto.setDest((String)dest.getSelectedItem());
                boolean a = new TrainDAO().sellProductDAO(productdto, u);
                loadDatas2();
                clear();
                
               
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_sellBttnMouseClicked
public void loadDatas2() {
        try {
             ResultSet rs = new TrainDAO().getBillNo();
            if (rs.next()) {
                int billno = new TrainDAO().getBill();
                int sum=billno+1;
                billNo.setText(Integer.toString(sum));
        }
        }catch (SQLException ex) {
            ex.printStackTrace();
        }
        billNo.setEditable(false);
        price.setEditable(false);
        price.setText("");
        Total.setEditable(false);
        Total.setText("");
    
    }
    
    private void cusnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cusnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cusnameActionPerformed

    private void typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeActionPerformed
        // TODO add your handling code here:
         int sellingPrice = new TrainDAO().getProductSellingPrice((String)source.getSelectedItem(),(String)dest.getSelectedItem(),(String)type.getSelectedItem());
                            price.setText(Integer.toString(sellingPrice));
    }//GEN-LAST:event_typeActionPerformed

    private void noofticketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noofticketsActionPerformed
        // TODO add your handling code here:
                            try{
                 int sellingPrice = Integer.parseInt(price.getText());
                 int totalRevenue = sellingPrice * Integer.parseInt((String )nooftickets.getSelectedItem());
                 Total.setText(Integer.toString(totalRevenue));                                
                            }
                            catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_noofticketsActionPerformed

    public void noofticks()
    {
            nooftickets.addItem("1");
            nooftickets.addItem("2");
            nooftickets.addItem("3");
            nooftickets.addItem("4");
            nooftickets.setSelectedItem(null);
    }
    public void loadDefaultDate() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        Date date = new Date();
        dateChooser.setDate((date));
    }
    public void loadCode() {
        try {
            //crs = .getRowSet();
            ResultSet rs = new TrainDAO().getCode();
            CachedRowSetImpl crs = new CachedRowSetImpl();
            while (rs.next()) {
                String list = rs.getString("train_no");
               // String list1 = rs.getString("type");
                System.out.println(list);
                traincode.addItem(list);
                traincode.setEditable(true);
                traincode.setSelectedItem(null);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    String list2="";
    String list3="";
    public void loadSource() {
        try {
            System.out.println("heellooo"+(String) traincode.getSelectedItem());
            ResultSet rs = new TrainDAO().getSource((String) traincode.getSelectedItem());
                if (rs.next()) {
                source.setEditable(true);
                list2 = rs.getString("source");
                System.out.println(list2);

                  
              // source.addItem(list2);
               //source.setEditable(true);
               // source.setSelectedItem(null);
                }                
        }
         catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
 public void loadDest() {
        try {
            ResultSet rs = new TrainDAO().getDest((String) traincode.getSelectedItem());
            while (rs.next()) {
                list3 = rs.getString("destination");
                //dest.addItem(list3);
                //dest.setEditable(true);
                //dest.setSelectedItem(null);

            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
      String loc[]={"Kanhangad","Nileshwar","Chervathur","payyanur","Kannur","vadakara","thalaserry","Kozhikode"};

 public void locSource()
 {
    
    // String s[]={"Kanhangad","Nileshwar","Chervathur","payyanur","Kannur","vadakara","thalaserry","Kozhikode"};
     for(int i=0;i<loc.length;i++)
     {
         if(loc[i].equalsIgnoreCase(list2))
         {
             while(!loc[i+1].equals(list3))
             {
         System.out.println("sourceis"+i);
         source.addItem(loc[i]);          
         i++;
             }
         break;    
         }
         
     }
     
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Total;
    private javax.swing.JTextField billNo;
    private javax.swing.JLabel billnolab;
    private javax.swing.JButton clear;
    private javax.swing.JTextField cusname;
    private javax.swing.JLabel customerNameLab;
    private javax.swing.JLabel customerNameLab1;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JComboBox<String> dest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> nooftickets;
    private javax.swing.JLabel pay;
    private javax.swing.JTextField price;
    private javax.swing.JLabel productCodeLab;
    private javax.swing.JLabel productCodeLab1;
    private javax.swing.JLabel productCodeLab2;
    private javax.swing.JLabel productCodeLab3;
    private javax.swing.JLabel productCodeLab4;
    private javax.swing.JLabel productCodeLab5;
    private javax.swing.JLabel productNameLab;
    private javax.swing.JLabel productNameLab1;
    private javax.swing.JLabel quantityLab;
    private javax.swing.JPanel salePanel;
    private javax.swing.JPanel salePanel1;
    private javax.swing.JLabel sellBttn;
    private javax.swing.JLabel sellingPriceLab;
    private javax.swing.JComboBox<String> source;
    private javax.swing.JComboBox<String> traincode;
    private javax.swing.JComboBox<String> type;
    // End of variables declaration//GEN-END:variables
}
